import packageJSON from './package.json'
import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const CREDITS = {
  name: `${packageJSON.theme.name} (v${packageJSON.version})`,
  author: packageJSON.author,
  version: packageJSON.version,
  description: packageJSON.theme.description,
  source: packageJSON.repository.url,
  website: packageJSON.theme.website,
  invite: packageJSON.theme.invite,
}

const generateCredits = () =>
  `// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT.\n\n/**\n  ${Object.entries(
    CREDITS,
  )
    .map(([key, value]) => {
      return `@${key} ${value}`
    })
    .join('\n  ')}\n`

console.log('(credits) generating...')
writeFile(resolve(__dirname, 'src/styles/credits.sass'), generateCredits())
  .then(() => console.log('(credits) done!'))
  .finally(() => process.exit(0))
